# Generated by Django 5.1 on 2024-08-17 18:52

import chats.helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=chats.helpers.get_chat_message_media_dir)),
                ('chats', models.ManyToManyField(related_name='messages', to='chats.chat')),
            ],
            options={
                'verbose_name': 'Chat message',
            },
        ),
    ]
